name: "fala-birinha"
description: "Seu assistente em ação"
author: "Camila Maia, Rodrigo Maia"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
