name: Momento de Auto-Reflexão.

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  testa-birinha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Testa o próprio Birinha
        uses: ./
        id: check
        with:
          trigger: '@deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
