name: Momento de Auto-Reflexão.

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - run: ls -la
    - name: Testa o próprio Birinha
      uses: ./
      id: check
      with:
        trigger: '@deploy'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: Find
      run: 'echo Found it!'
      if: steps.check.outputs.triggered == 'true'
